theme: jekyll-theme-minimal
title: Vitali Brunovski
description: Performance Engineer
logo: https://res.infoq.com/articles/lessons-learned-performance-testing/en/headerimage/lessons-learned-in-performance-testing-logo-big-1574070299646.jpg
show_downloads: false
